#!/usr/bin/env python
import sys
import optparse
import os
sys.path.append('../')
sys.path.append('./')
from repoman_client import repoman_client

repo = repoman_client.repoman_client()

parser = optparse.OptionParser()

def ask_yes_or_no(*args, **kwargs):
    try:
        force = kwargs['force']
    except:
        force = False
    print " Are you sure you want to continue?"
    if force:
        print " To prevent this message from displaying, run the command with" 
        print " --force or -f."
    k=raw_input("[y/N]")
    if k in ('y', 'ye', 'yes'):
        return True
    return False

def print_help_menu():
    print "repoman-client 0.1.1"
    print " "
    print "Available commands:"
    print "repoman list [--all]"
    print "repoman getuser [--all]"
    print "repoman info --name imagename "
    print "repoman save --force --name imagename [--(any other metadata tags)]"
    print "repoman get --name imagename"
    print "repoman delete --name imagename [--force]"
    print "repoman update [--force] --name imagename [--(any other metadata tags)]"
    print "repoman upload --file filename --name imagename [--(any other metadata tags)]"
    print "repoman share (--user username | --group groupname)  --name vmname"
    print "repoman unshare (--user username | --group groupname)  --name  vmname"
    print "repoman --help or repoman help"
    print "\n"
    print "Other metadata tag examples: --hypervisor Xen, --os_variant RHEL"
    print "All defaults are set in repoman-client.conf, set in /etc/repoman-client/repoman-client.conf by default.  User configs can be placed at ~/repoman-client."
    print " "
    sys.exit(0)

def main():
    if not len(sys.argv) > 1:
        print_help_menu()
        sys.exit(0)
    else:
        command = sys.argv[1]
        # args = sys.argv[1:]

    if command == 'list':
        parser.add_option('-l','--long',dest='long',default=False)
        parser.add_option('-a','--all',dest="all",default=False,action="store_true")
        options, args = parser.parse_args(args=sys.argv[2:])
        if options.all:
            repo.list_all_images()
        else:
            repo.list_images()
        sys.exit(0)

    if command == 'save':
        args = sys.argv
        force = False
        for arg in args:
            if arg == '--force':
                force = True
                args.remove(arg)
        metadata = dict([(args[i].strip('-'), args[i+1]) for i in range(2, len(args) - 1, 2)])
        image_list = repo.list_images_raw()
        for i in xrange(len(repo.list_images_raw())):
            image_list[i] = repo.list_images_raw()[i].split('/')[6]

        try:
            name = metadata['name']

        except:
            print '''    Please either specify an image name with the --name flag
        or specify metadata with --name [name] --os_type [os_type] etc..
        The images available to you are:
                  ''' 
            for item in image_list:
                print item
            print '''
        select one of these images to overwrite, or specify a new image name
        see --help for more details
                  '''
            sys.exit(2)
        replace=False
        for item in image_list:
            if item == name:
                replace=True
                if not force:
                    print 'WARNING!! This image already exists on the repository.'
                    if not ask_yes_or_no(force=True):
                        print 'Exiting repoman-client.'
                        sys.exit(2)
        print "Saving image "+name+" with the following metadata:"
        for key in metadata:
            print key+": "+metadata[key]
        repo.save_image(metadata=metadata,replace=replace)
        sys.exit(0)

    if command == 'getuser':
        parser.add_option('-a','--all',dest="all",default=False,action="store_true")
        options, args = parser.parse_args(args=sys.argv[2:])
        if options.all:
            repo.list_users()
            sys.exit(0)
        else:
            repo.get_user()
        sys.exit(0)

    if command == 'info':
        image_list = repo.list_images_raw()
        for i in xrange(len(repo.list_images_raw())):
            image_list[i] = repo.list_images_raw()[i].split('/')[6]

        parser.add_option('-n','--name',action="store",type="string",dest="name")
        options, args = parser.parse_args(args=sys.argv[2:])
        if options.name:
            resp = repo.get_image_info(options.name)
            print '\n'
            for key in resp:
                print "  "+key+": \t",
                print str(resp[key])
            print '\n'
            sys.exit(0)           
        else:
            print "Please run this command as info --name image_name, where image_name is one of the following:"
            for item in image_list:
                print item
            sys.exit(2)
        sys.exit(0)


    if command == 'upload':
        args = sys.argv
        metadata = dict([(args[i].strip('-'), args[i+1]) for i in range(2, len(args) - 1, 2)])
        # Check if file to upload has been specified
        try:
            file = metadata['file']
            del metadata['file']
        except:
            print "Please specify a file to upload with --file file_name"
            sys.exit(0)
        if not os.path.isfile(file):
            print "The file "+file+" does not exist.  Please try again."
            sys.exit(0)
        try:
            name = metadata['name']
        except:
            print "The minimum metadata needed to upload an image is the name, specified with --name"
            sys.exit(0)
        
        #Server is expecting Bool objects for readonly
        try:
            readonly = metadata['readonly']
            true_values = ['t', 'True', 'true']
            if true_values.count(metadata['readonly']):
                metadata['readonly'] = True
            else:
                metadata['readonly'] = False
        except:
            metadata['readonly'] = False
        image_list = repo.list_images_raw()
        for i in xrange(len(repo.list_images_raw())):
            image_list[i] = repo.list_images_raw()[i].split('/')[6]
        print "Uploading..."
        replace=False
        for item in image_list:
            if item == metadata['name']:
                replace=True
                print 'WARNING!! This image already exists on the repository.'
                if not ask_yes_or_no():
                    print 'Exiting repoman-client.'
                    sys.exit(2)
        repo.upload_image(file, replace=replace, name=name, metadata=metadata)
        sys.exit(0)

    if command == 'get':
        parser.add_option('-n','--name',action="store",type="string",dest="name")
        parser.add_option('-p','--path',action="store",type="string",dest="path")
        options, args = parser.parse_args(args=sys.argv[2:])
        image_list = repo.list_images_raw()
        for i in xrange(len(repo.list_images_raw())):
            image_list[i] = repo.list_images_raw()[i].split('/')[6]
        if not options.name:
            print "Please enter on of the following names:"
            for item in image_list:
                print item
        else:
            exists = False
            for item in image_list:
                if item == options.name:
                    exists = True
            if exists:
                if options.path:
                    repo.get(name=options.name,path=options.path)
                else:
                    repo.get(name=options.name)
            else: 
               print "Image did not match any of your images on the server."
               print "Please enter on of the following names:"           
               for item in image_list:
                   print item
        sys.exit(0)                        
    
    if command == "update":
        args = sys.argv
        if len(args) < 3:
            print "To create or update metadata on the repository:"
            print "update --name image_name (any other metadata, i.e. --os_type OSType)"
            sys.exit(0)
        force = False
        for arg in args:
            if arg == '--force':
                force = True
                args.remove(arg)
        metadata = dict([(args[i].strip('-'), args[i+1]) for i in range(2, len(args) - 1, 2)])
        try:
            name = metadata['name']
        except:
            print "Please enter at least a name as metadata."
            sys.exit(0)
        
        #Server is expecting Bool objects for readonly
        try:
            readonly = metadata['readonly']
            true_values = ['t', 'True', 'true']
            if true_values.count(metadata['readonly']):
                metadata['readonly'] = True
            else:
                metadata['readonly'] = False
        
        except:
            metadata['readonly'] = False

        image_list = repo.list_images_raw()
        exists = False
        for i in xrange(len(repo.list_images_raw())):
            image_list[i] = repo.list_images_raw()[i].split('/')[6]
            if image_list[i] == name:
                exists = True
        if not force and exists:
            print "Warning! This image name already has metadata on the server."
            if ask_yes_or_no(force=True):
                print "Updating image "+name+" with metadata: "
                for key in metadata:
                    print key+": "+str(metadata[key])
                repo.update_metadata(metadata=metadata, exists=exists)
            else:
                print "Exiting repoman."
                sys.exit(0)
        else:
            print "Updating image "+name+" with metadata: "
            for key in metadata:
                print key+": "+str(metadata[key])
            repo.update_metadata(metadata=metadata, exists=exists)
        sys.exit(0)
           
 
    if command == "delete":
        parser.add_option('-n','--name',action="store", type="string",dest="name")
        parser.add_option('-f','--force',dest="force",default=False,action="store_true")
        options, args = parser.parse_args(args=sys.argv[2:])    
        if not options.name:
            print "Please specify a name with --name image_name"
            sys.exit(0)
        image_list = repo.list_images_raw()
        exists = False
        for i in xrange(len(repo.list_images_raw())):
            image_list[i] = repo.list_images_raw()[i].split('/')[6]
            if image_list[i] == options.name:
                exists = True
        if not exists:
            print "That image does not exist on the repository."
        else:
            print "Deleting image "+options.name
            if options.force:
                repo.delete(options.name)
                sys.exit(2)
            if ask_yes_or_no(force=options.force):
                repo.delete(options.name)
            else:
                print "Exiting repoman."
                sys.exit(0)
        sys.exit(0)

    if command == "share":
        parser.add_option('-u','--username',action="store", type="string",dest="username")
        parser.add_option('-g','--group',action="store", type="string",dest="group")
        parser.add_option('-n','--name',action="store", type="string",dest="image")
        options, args = parser.parse_args(args=sys.argv[2:])
        if not options.username and not options.group:
            print "Please user either a user or a group to share the image with."
            print "i.e. share --user username or share --group groupname --name imagename"
            sys.exit(0)
        if options.username and options.group:
            print "Please select either a user or a group to share to."
            sys.exit(0)
        if not options.image:
            image_list = repo.list_images_raw()
            for i in xrange(len(repo.list_images_raw())):
                image_list[i] = repo.list_images_raw()[i].split('/')[6]
            print "Please enter an image to share."
            print "i.e. share --user username --name imagename"
            print "The images you own on the server are:"
            for item in image_list:
                print item
            sys.exit(2)
        if options.username:
            repo.share_user(user=options.username,image=options.image)
            sys.exit(0)
        if options.group:
            repo.share_group(group=options.group,image=options.image)
            sys.exit(0)
        sys.exit(0)     

    if command == "unshare":
        parser.add_option('-u','--username',action="store", type="string",dest="username")
        parser.add_option('-g','--group',action="store", type="string",dest="group")
        parser.add_option('-n','--name',action="store", type="string",dest="image")
        options, args = parser.parse_args(args=sys.argv[2:])
        image_list = repo.list_images_raw()
        for i in xrange(len(repo.list_images_raw())):
            image_list[i] = repo.list_images_raw()[i].split('/')[6]
        if not options.username and not options.group:
            print "Please user either a user or a group to unshare the image with."
            print "i.e. unshare --user username or unshare --group groupname --name imagename"
            sys.exit(0)
        if options.username and options.group:
            print "Please select either a user or a group to unshare to."
            sys.exit(0)
        if not options.image:
            print "Please enter an image to unshare."
            print "i.e. unshare --user username --name imagename"
            print "The images you own on the server are:"
            for item in image_list:
                print item
            sys.exit(0)
        exists = False
        for item in image_list:
            if item == options.image:
                exists = True
        if not exists:
            print "That image does not exist on the repository."
            print "The images you own on the server are:"
            for item in image_list:
                print item
            sys.exit(0) 
        if options.username:    
            repo.unshare_user(user=options.username,image=options.image)
            sys.exit(2)
        if options.group:
            repo.unshare_group(group=options.group,image=options.image) 
            sys.exit(2)
        sys.exit(0)
        
    if command == 'help' or command == '--help':
        print_help_menu()
        sys.exit(0)
    
    else:
        print "Command not recognized."
        print_help_menu()
        sys.exit(0)

if __name__ == "__main__":
    main() 
