#!/usr/bin/env python
'''
Created on Sep 17, 2010

@author: fransham
'''
import getopt
import pwd
import sys
import os
import getpass
from repoclient import repoclient


repo = "localhost"
    
def usage():
    print "coming soon stay tuned"
    
    
def ask_yes_or_no():
    print " Are you sure you want to continue?"
    k=raw_input("[y/N]")
    if k in ('y', 'ye', 'yes'):
        return True
    return False

def main(argv):
    try:
        opts, args = getopt.getopt(argv, "hd",
                                   ["help",
                                    "debug",
                                    "list",
                                    "getuser",
                                    "all",
                                    "save",
                                    "name=",
                                    "user=",
                                    "repo="
                                    ])
        
    except getopt.GetoptError:
        usage()
        sys.exit(2)
                           
    list = False
    getuser = False
    getallusers=False
    save = False
    username = pwd.getpwuid(os.getuid()).pw_name
    userid=0
    name = ""
    newname = ""
    
    repo = repoclient.repoclient()
    
    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        elif opt == ("-d", "--debug"):
            global _debug
            _debug = 1
        elif opt in ("--list"):
            list = True
        elif opt in ("--getuser"):
            getuser = True
        elif opt in ("--save"):
            save = True
        elif opt in ("--name"):
            name = arg
        elif opt in ("--user"):
            userid = arg
        elif opt in ("--repo"):
            repo = arg
        elif opt in ("--all"):
            getallusers = True
    
    #make sure only one command line argument is specified:
    if( list + getuser + save != 1):
        usage()
        sys.exit(2)
      

    if list:
        repo.list_images()
        sys.exit(0)
        
    if getuser:
        if getallusers:
            repo.list_users()
        else:
            repo.get_user()
        sys.exit(0)
        
    if save:
        if not name:
            print '''
    Please specify an image name with the --name flag.
    The images available to you are:
            '''
            repo.list_images()
            print '''
    select one of these images to overwrite, or specify a new image name
    see --help for more details
            '''
            sys.exit(2)
        repo.save_image(name)
        sys.exit(0) 
        
        
if __name__ == "__main__":
    main(sys.argv[1:])
